apiVersion: v1
kind: Service
metadata:
  name: pokeapp-service
  namespace: spinnaker
spec:
  selector:
    app: pokeapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer