apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  namespace: spinnaker
  labels:
    app: spin
    cluster: spin-gate
  name: spin-gate-public
spec:
  ports:
  - port: 8084
    protocol: TCP
    targetPort: 8084
  selector:
    app: spin
    cluster: spin-gate
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  namespace: spinnaker
  labels:
    app: spin
    cluster: spin-deck
  name: spin-deck-public
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: spin
    cluster: spin-deck
  type: LoadBalancer
status:
  loadBalancer: {}
